import type { SceneObjectKind, Vector2 } from "@/shared/types";

export const PRESET_SCENE_CATEGORY_ORDER = [
  { id: "indoor", label: "室内家居" },
  { id: "school", label: "校园课堂" },
  { id: "cafe", label: "店面商业" },
  { id: "urban", label: "街景都市" },
  { id: "nature", label: "自然户外" },
  { id: "fantasy", label: "和风奇幻" },
  { id: "props", label: "演出小道具" },
] as const;

export type PresetSceneCategory = (typeof PRESET_SCENE_CATEGORY_ORDER)[number]["id"];

export type PresetSceneObjectDefinition = {
  /** Stable id stored on `SceneObject.presetKey` and used for dedupe in the UI. */
  key: string;
  label: string;
  name: string;
  description: string;
  fill: string;
  size: { width: number; height: number };
  kind: Extract<SceneObjectKind, "preset">;
  category: PresetSceneCategory;
};

export const PRESET_SCENE_OBJECTS: PresetSceneObjectDefinition[] = [
  {
    key: "preset-table",
    label: "桌子",
    name: "木桌",
    description: "a wooden table, anime interior prop",
    fill: "#b45309",
    size: { width: 200, height: 80 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-window",
    label: "窗户",
    name: "窗户",
    description: "a window with soft daylight, anime room",
    fill: "#bae6fd",
    size: { width: 120, height: 160 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-bed",
    label: "床",
    name: "双人床",
    description: "an anime-style double bed with pillows",
    fill: "#fbcfe8",
    size: { width: 220, height: 120 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-sofa",
    label: "沙发",
    name: "沙发",
    description: "a cozy sofa, slice-of-life anime living room",
    fill: "#78716c",
    size: { width: 200, height: 90 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-bookshelf",
    label: "书架",
    name: "书架",
    description: "a tall bookshelf filled with books, otaku room",
    fill: "#57534e",
    size: { width: 85, height: 200 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-floor-lamp",
    label: "落地灯",
    name: "落地灯",
    description: "a slim floor lamp, warm indoor lighting",
    fill: "#fbbf24",
    size: { width: 40, height: 185 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-mirror",
    label: "穿衣镜",
    name: "穿衣镜",
    description: "a full-length mirror, dressing corner",
    fill: "#e2e8f0",
    size: { width: 70, height: 200 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-door",
    label: "房门",
    name: "房门",
    description: "an interior wooden door, hallway or bedroom",
    fill: "#a8a29e",
    size: { width: 90, height: 200 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-curtains",
    label: "窗帘",
    name: "窗帘",
    description: "soft window curtains, gentle backlight",
    fill: "#fce7f3",
    size: { width: 140, height: 220 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-study-desk",
    label: "书桌",
    name: "书桌",
    description: "a study desk with simple clutter, student room",
    fill: "#78716c",
    size: { width: 160, height: 75 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-chair",
    label: "椅子",
    name: "单人椅",
    description: "a simple chair, interior seating",
    fill: "#64748b",
    size: { width: 70, height: 85 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-kitchen-counter",
    label: "厨台",
    name: "厨台",
    description: "a kitchen counter island, domestic scene",
    fill: "#cbd5e1",
    size: { width: 240, height: 70 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-fridge",
    label: "冰箱",
    name: "冰箱",
    description: "a refrigerator, kitchen background",
    fill: "#f1f5f9",
    size: { width: 90, height: 200 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-bathtub",
    label: "浴缸",
    name: "浴缸",
    description: "a bathtub with steam hint, bathroom scene",
    fill: "#bae6fd",
    size: { width: 180, height: 70 },
    kind: "preset",
    category: "indoor",
  },
  {
    key: "preset-school-desk",
    label: "课桌",
    name: "课桌",
    description: "a classroom student desk, school anime",
    fill: "#d6d3d1",
    size: { width: 100, height: 60 },
    kind: "preset",
    category: "school",
  },
  {
    key: "preset-blackboard",
    label: "黑板",
    name: "黑板",
    description: "a classroom blackboard with chalk dust",
    fill: "#1e293b",
    size: { width: 280, height: 100 },
    kind: "preset",
    category: "school",
  },
  {
    key: "preset-lockers",
    label: "储物柜",
    name: "储物柜",
    description: "school hallway lockers, corridor scene",
    fill: "#64748b",
    size: { width: 160, height: 200 },
    kind: "preset",
    category: "school",
  },
  {
    key: "preset-gym-mat",
    label: "体操垫",
    name: "体操垫",
    description: "gymnasium exercise mats, sports club",
    fill: "#fca5a5",
    size: { width: 180, height: 90 },
    kind: "preset",
    category: "school",
  },
  {
    key: "preset-rooftop-rail",
    label: "天台护栏",
    name: "天台护栏",
    description: "rooftop handrail silhouette, school drama skyline",
    fill: "#94a3b8",
    size: { width: 280, height: 55 },
    kind: "preset",
    category: "school",
  },
  {
    key: "preset-cafe-counter",
    label: "吧台",
    name: "吧台",
    description: "a cafe counter, maid cafe or kissaten",
    fill: "#78350f",
    size: { width: 200, height: 90 },
    kind: "preset",
    category: "cafe",
  },
  {
    key: "preset-pastry-case",
    label: "展示柜",
    name: "展示柜",
    description: "a pastry display case, bakery shop",
    fill: "#fef3c7",
    size: { width: 120, height: 160 },
    kind: "preset",
    category: "cafe",
  },
  {
    key: "preset-shop-shelf",
    label: "货架",
    name: "货架",
    description: "convenience store shelves with products",
    fill: "#e7e5e4",
    size: { width: 200, height: 180 },
    kind: "preset",
    category: "cafe",
  },
  {
    key: "preset-vending-machine",
    label: "自贩机",
    name: "自动售货机",
    description: "a Japanese vending machine, street corner",
    fill: "#dc2626",
    size: { width: 85, height: 185 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-bench",
    label: "长椅",
    name: "公园长椅",
    description: "a park bench, quiet urban pause",
    fill: "#78716c",
    size: { width: 160, height: 50 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-street-lamp",
    label: "路灯",
    name: "路灯",
    description: "a street lamp post, night city mood",
    fill: "#fbbf24",
    size: { width: 40, height: 220 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-fence",
    label: "围栏",
    name: "围栏",
    description: "a wooden or metal fence, alley depth",
    fill: "#d97706",
    size: { width: 240, height: 70 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-building-silhouette",
    label: "楼群剪影",
    name: "楼群剪影",
    description: "city buildings silhouette, anime skyline backdrop",
    fill: "#1e293b",
    size: { width: 320, height: 160 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-crosswalk",
    label: "路口路面",
    name: "斑马线",
    description: "a crosswalk road segment, shibuya-style street",
    fill: "#334155",
    size: { width: 300, height: 85 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-train-platform",
    label: "站台",
    name: "站台边缘",
    description: "train station platform edge, commute scene",
    fill: "#94a3b8",
    size: { width: 280, height: 60 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-overpass",
    label: "天桥",
    name: "天桥剪影",
    description: "an elevated walkway or overpass silhouette",
    fill: "#475569",
    size: { width: 260, height: 50 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-neon-block",
    label: "霓虹块",
    name: "霓虹招牌块",
    description: "a neon sign color block, cyberpunk city accent",
    fill: "#e879f9",
    size: { width: 120, height: 40 },
    kind: "preset",
    category: "urban",
  },
  {
    key: "preset-tree",
    label: "树",
    name: "树",
    description: "a stylized green tree, outdoor background",
    fill: "#166534",
    size: { width: 100, height: 180 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-cherry-tree",
    label: "樱花树",
    name: "樱花树",
    description: "a cherry blossom tree, spring sakura scene",
    fill: "#fbcfe8",
    size: { width: 120, height: 200 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-bush",
    label: "灌木",
    name: "灌木丛",
    description: "a green hedge or bush cluster",
    fill: "#15803d",
    size: { width: 140, height: 100 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-water-surface",
    label: "水面",
    name: "水面",
    description: "calm water surface, lakeside or pool",
    fill: "#38bdf8",
    size: { width: 280, height: 65 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-mountain-range",
    label: "远山",
    name: "远山",
    description: "layered distant mountains, landscape backdrop",
    fill: "#64748b",
    size: { width: 320, height: 120 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-grass-field",
    label: "草地",
    name: "草地",
    description: "a grass field foreground block, picnic or sports",
    fill: "#22c55e",
    size: { width: 260, height: 90 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-beach-sand",
    label: "沙滩",
    name: "沙滩",
    description: "beach sand strip, summer seaside",
    fill: "#fde68a",
    size: { width: 280, height: 75 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-moon",
    label: "月亮",
    name: "月亮",
    description: "a crescent moon, night sky element",
    fill: "#fef9c3",
    size: { width: 80, height: 80 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-clouds",
    label: "云朵",
    name: "云朵",
    description: "stylized cloud shapes, open sky",
    fill: "#f8fafc",
    size: { width: 200, height: 70 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-rain-streak",
    label: "雨幕",
    name: "雨线",
    description: "rain streak overlay block, melancholic weather",
    fill: "#94a3b8",
    size: { width: 280, height: 100 },
    kind: "preset",
    category: "nature",
  },
  {
    key: "preset-torii",
    label: "鸟居",
    name: "鸟居",
    description: "a torii gate, shrine entrance",
    fill: "#dc2626",
    size: { width: 140, height: 200 },
    kind: "preset",
    category: "fantasy",
  },
  {
    key: "preset-stone-lantern",
    label: "石灯笼",
    name: "石灯笼",
    description: "a Japanese stone lantern, temple garden",
    fill: "#78716c",
    size: { width: 50, height: 90 },
    kind: "preset",
    category: "fantasy",
  },
  {
    key: "preset-magic-circle",
    label: "魔法阵",
    name: "魔法阵",
    description: "a magic circle on the ground, fantasy ritual",
    fill: "#a78bfa",
    size: { width: 160, height: 160 },
    kind: "preset",
    category: "fantasy",
  },
  {
    key: "preset-crystal",
    label: "水晶",
    name: "水晶簇",
    description: "a crystal cluster, isekai or magical girl",
    fill: "#818cf8",
    size: { width: 80, height: 120 },
    kind: "preset",
    category: "fantasy",
  },
  {
    key: "preset-castle-tower",
    label: "城堡塔",
    name: "城堡塔",
    description: "a fantasy castle tower silhouette",
    fill: "#94a3b8",
    size: { width: 90, height: 240 },
    kind: "preset",
    category: "fantasy",
  },
  {
    key: "preset-bridge-arch",
    label: "拱桥",
    name: "拱桥剪影",
    description: "a stone bridge arch, river fantasy",
    fill: "#57534e",
    size: { width: 220, height: 90 },
    kind: "preset",
    category: "fantasy",
  },
  {
    key: "preset-umbrella",
    label: "阳伞",
    name: "阳伞",
    description: "a parasol umbrella, date scene prop",
    fill: "#f472b6",
    size: { width: 90, height: 90 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-school-bag",
    label: "书包",
    name: "书包",
    description: "an anime school bag randoseru or tote",
    fill: "#3b82f6",
    size: { width: 55, height: 65 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-microphone",
    label: "立麦",
    name: "立麦",
    description: "a standing microphone, idol or concert",
    fill: "#64748b",
    size: { width: 28, height: 140 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-stage-light",
    label: "舞台灯",
    name: "舞台射灯",
    description: "a stage spotlight beam block",
    fill: "#fbbf24",
    size: { width: 60, height: 60 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-heart-balloon",
    label: "爱心气球",
    name: "爱心气球",
    description: "heart-shaped balloons, festival or romance",
    fill: "#fb7185",
    size: { width: 55, height: 75 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-street-sign",
    label: "路牌",
    name: "路牌",
    description: "a blank street sign, urban navigation prop",
    fill: "#fef08a",
    size: { width: 70, height: 50 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-baseball-bat",
    label: "球棒",
    name: "棒球棍",
    description: "a baseball bat prop, sports or delinquent gag",
    fill: "#ca8a04",
    size: { width: 120, height: 28 },
    kind: "preset",
    category: "props",
  },
  {
    key: "preset-sword-silhouette",
    label: "刀剑剪影",
    name: "刀剑",
    description: "a stylized sword silhouette, battle fantasy",
    fill: "#cbd5e1",
    size: { width: 140, height: 36 },
    kind: "preset",
    category: "props",
  },
];

export function defaultLineEndpoints(width: number, height: number) {
  return {
    x1: 0,
    y1: height / 2,
    x2: width,
    y2: height / 2,
  };
}

/** Isosceles triangle filling the layout box (top vertex centered). */
export function defaultPolygonPoints(width: number, height: number): Vector2[] {
  return [
    { x: width / 2, y: 0 },
    { x: width, y: height },
    { x: 0, y: height },
  ];
}
