import type { PromptTag } from "@/shared/types";

export const BUILT_IN_PROMPT_LIBRARY_TAGS: PromptTag[] = [
  {
    id: "library-cinematic",
    label: "电影感",
    prompt: "cinematic composition",
    category: "style",
    subcategory: "style-composition",
    weight: { enabled: true, value: 1.15 },
  },
  {
    id: "library-soft-light",
    label: "柔和光线",
    prompt: "soft light",
    category: "lighting",
    subcategory: "lighting-mood",
    weight: { enabled: true, value: 1.1 },
  },
  {
    id: "library-high-quality",
    label: "高质量",
    prompt: "high quality, detailed illustration",
    category: "quality",
    subcategory: "quality-finish",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-long-hair",
    label: "长发",
    prompt: "long flowing hair",
    category: "body-part",
    subcategory: "body-part-hair",
    weight: { enabled: true, value: 1.2 },
  },
  {
    id: "library-blue-eyes",
    label: "蓝色眼睛",
    prompt: "blue eyes",
    category: "body-part",
    subcategory: "body-part-eyes",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-holding-sword",
    label: "手持剑",
    prompt: "holding a sword",
    category: "body-part",
    subcategory: "body-part-hands",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-standing-pose",
    label: "自然站姿",
    prompt: "standing naturally",
    category: "character",
    subcategory: "character-pose",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-casual-top",
    label: "休闲上衣",
    prompt: "casual shirt",
    category: "outfit",
    subcategory: "outfit-upper",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-misty-background",
    label: "雾气背景",
    prompt: "misty background",
    category: "scene",
    subcategory: "scene-background",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-negative-low-quality",
    label: "低质量",
    prompt: "low quality",
    category: "negative",
    subcategory: "negative-quality",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-extra-fingers",
    label: "多余手指",
    prompt: "extra fingers",
    category: "negative",
    subcategory: "negative-anatomy",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-cgi",
    label: "CGI 感",
    prompt: "CGI",
    category: "negative",
    subcategory: "negative-artifact",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-3d-render",
    label: "3D 渲染感",
    prompt: "3D render",
    category: "negative",
    subcategory: "negative-artifact",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-over-smoothed-skin",
    label: "过度磨皮",
    prompt: "over-smoothed skin",
    category: "negative",
    subcategory: "negative-artifact",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-plastic-skin",
    label: "塑料皮肤",
    prompt: "plastic skin",
    category: "negative",
    subcategory: "negative-artifact",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-overly-glossy",
    label: "过度油亮",
    prompt: "overly glossy",
    category: "negative",
    subcategory: "negative-artifact",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-unnatural-symmetry",
    label: "不自然对称",
    prompt: "unnatural symmetry",
    category: "negative",
    subcategory: "negative-composition",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-saturated-colors",
    label: "过饱和色彩",
    prompt: "saturated colors",
    category: "negative",
    subcategory: "negative-quality",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
  {
    id: "library-negative-digital-airbrush",
    label: "数码喷枪感",
    prompt: "digital airbrush",
    category: "negative",
    subcategory: "negative-artifact",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
];
