import type { PromptTag } from "@/shared/types";

export const BUILT_IN_PROMPT_LIBRARY_TAGS: PromptTag[] = [
  {
    id: "library-cinematic",
    label: "电影感",
    prompt: "cinematic composition",
    category: "style",
    subcategory: "style-composition",
    weight: { enabled: true, value: 1.15 },
  },
  {
    id: "library-soft-light",
    label: "柔和光线",
    prompt: "soft light",
    category: "lighting",
    subcategory: "lighting-mood",
    weight: { enabled: true, value: 1.1 },
  },
  {
    id: "library-high-quality",
    label: "高质量",
    prompt: "high quality, detailed illustration",
    category: "quality",
    subcategory: "quality-finish",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-long-hair",
    label: "长发",
    prompt: "long flowing hair",
    category: "body-part",
    subcategory: "body-part-hair",
    weight: { enabled: true, value: 1.2 },
  },
  {
    id: "library-blue-eyes",
    label: "蓝色眼睛",
    prompt: "blue eyes",
    category: "body-part",
    subcategory: "body-part-eyes",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-holding-sword",
    label: "手持剑",
    prompt: "holding a sword",
    category: "body-part",
    subcategory: "body-part-hands",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-standing-pose",
    label: "自然站姿",
    prompt: "standing naturally",
    category: "character",
    subcategory: "character-pose",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-misty-background",
    label: "雾气背景",
    prompt: "misty background",
    category: "scene",
    subcategory: "scene-background",
    weight: { enabled: false, value: 1 },
  },
  {
    id: "library-negative-low-quality",
    label: "低质量负面",
    prompt: "low quality, blurry",
    category: "negative",
    subcategory: "negative-quality",
    weight: { enabled: false, value: 1 },
    negative: true,
  },
];
